actor_learning_rate: 3e-4
critic_learning_rate: 3e-4
dataset_name: antmaze-large-diverse-v2
expectile: 0.9
gamma: 0.99
log_std_max: 2.0
log_std_min: -20.0
normalize_reward: true
normalize_states: true
state_dependent_std: true
tanh_squash_distribution: false
tau: 0.005
temperature: 6.0
eval_episodes: 100
eval_every: 50
l1_ratio: 0.5
actor_dropout: 0.1
actor_ln: true
actor_wd: 0.01