actor_bc_aux_loss: "sum"
actor_bc_aux_weight: 0.03
actor_bc_coef: 0.01
actor_bc_noise: 0.01
actor_ema_tau: 0.005
actor_grad_noise: 0.0003
actor_learning_rate: 0.0001
actor_wd: 0.003
batch_size: 1024
critic_dropout: 0.03
critic_grad_noise: 0.0001
critic_learning_rate: 0.003
critic_n_hiddens: 5
critic_next_state_pred_epochs: 1000
critic_objective_noise: 0
critic_warmup_epochs: 100
critic_wd: 3e-05
dataset_name: hopper-random-v2
eval_episodes: 10
eval_every: 200
gamma: 0.999
il_warmup_epochs: 50
nf_base_dist: "uniform"
nf_det_layers: 2
nf_dropout: 0.1
nf_eval_num_samples: 16
nf_eval_z_scale: 1
nf_hidden_dim: 512
nf_n_hiddens: 4
nf_num_layers: 6
nf_scale_max: 0.75
nf_use_plu: true
normalize_reward: false
num_critics: 4
num_epochs: 1000
optimizer_type: "adam"
policy_noise: 0
q_infer_step_size: 0.01
q_infer_steps: 0
tau: 0.003
use_actor_ema: true
use_distributional: true
use_iql: false
use_nf: true
use_prev_action: false
use_prev_state: true
use_target_actor: false
