activation: "gsp"
actor_bc_aux_loss: "sum"
actor_bc_aux_weight: 0.01
actor_bc_coef: 0.01
actor_bc_noise: 0.0011527150088694314
actor_ema_tau: 0.005
actor_grad_noise: 0.0002592457561662737
actor_learning_rate: 4.1267685316003e-05
actor_wd: 9.63228148582001e-06
batch_size: 512
critic_dropout: 0.004812813019710172
critic_grad_noise: 5.037219341185508e-06
critic_learning_rate: 2.3933259595983062e-05
critic_n_hiddens: 5
critic_next_state_pred_epochs: 2000
critic_objective_noise: 0
critic_warmup_epochs: 200
critic_wd: 3.685090240381485e-05
dataset_name: relocate-human-v1
eval_episodes: 10
eval_every: 1000
gamma: 0.999
il_warmup_epochs: 100
n_classes: 201
n_step: 1
nf_base_dist: "uniform"
nf_det_layers: 2
nf_dropout: 0.04812220593485498
nf_eval_num_samples: 32
nf_eval_z_scale: 1
nf_hidden_dim: 256
nf_n_hiddens: 2
nf_num_layers: 14
nf_scale_max: 0.75
nf_use_plu: true
normalize_reward: false
num_critics: 4
num_epochs: 1000
optimizer_type: "kron"
policy_noise: 0.2
q_infer_step_size: 0.01
q_infer_steps: 2
target_action_k: 1
target_action_reduction: "mean"
target_critic_aggregation: "mean"
tau: 0.007310827254552789
use_actor_ema: true
use_distributional: true
use_iql: false
use_nf: true
use_prev_action: false
use_prev_state: false
use_target_actor: false
