actor_learning_rate: 3e-4
critic_learning_rate: 3e-4
dataset_name: hammer-human-v1
expectile: 0.9
gamma: 0.99
log_std_max: 2.0
log_std_min: -20.0
normalize_reward: false
normalize_states: true
state_dependent_std: true
tanh_squash_distribution: false
tau: 0.005
temperature: 10.0
actor_dropout: 0.0
actor_ln: false
actor_wd: 0.01