command:
- ${env}
- PYTHONPATH=.
- python3
- ${program}
- ${args}
method: grid
metric:
  goal: maximize
  name: eval/normalized_score_mean
parameters:
  config_path:
    values:
    - configs/offline/rebrac-plus-ogbench/cube/double_play_singletask_v0.yaml
    - configs/offline/rebrac-plus-ogbench/antmaze/giant_navigate_singletask_v0.yaml
    - configs/offline/rebrac-plus-ogbench/scene/play_singletask_v0.yaml
    - configs/offline/rebrac-plus-ogbench/humanoidmaze/large_navigate_singletask_v0.yaml
    - configs/offline/rebrac-plus-ogbench/puzzle/4x4_play_singletask_v0.yaml
  train_seed:
    values:
    - 10
    - 11
    - 12
    - 13
  optimizer_type:
    value: adam
  group:
    value: abl-04-adam
program: algorithms/rebrac_cl_plus_ogbench.py
